const LANGUAGES = {
  es: {
    appTitle: "Duck Timer",
    settingsTitle: "Ajustes",
    labelAppearance: "Apariencia",
    labelLanguage: "Idioma",
    labelMaxTimers: "Máximo de Temporizadores",
    labelSupport: "Soporte y Sugerencias",
    labelPrivacy: "Política de Privacidad",
    labelVersion: "Versión",
    btnAccept: "ACEPTAR",
    btnCancel: "CANCELAR",
    btnStopAlarm: "DETENER ALARMA",
    privacyTitle: "Política de Privacidad",
    privacyText: "Duck Timer valora tu privacidad. Esta aplicación: No recopila datos personales, no comparte información con terceros y utiliza el almacenamiento local para guardar tus preferencias.",
    newTimerTitle: "Nuevo Temporizador",
    modeDuck: "Patito",
    modeDigital: "Digital",
    timeUpBody: "¡El tiempo ha terminado!",
    emptyTimeAlert: "¡Marca un tiempo primero!",
    maxTimersAlert: "Has alcanzado el límite de:",
    labelVibration: "Vibración al terminar",
    labelVersion: "Versión 1.0.0"
  },
  en: {
    appTitle: "Duck Timer",
    settingsTitle: "Settings",
    labelAppearance: "Appearance",
    labelLanguage: "Language",
    labelMaxTimers: "Max Timers",
    labelSupport: "Support & Suggestions",
    labelPrivacy: "Privacy Policy",
    labelVersion: "Version",
    btnAccept: "ACCEPT",
    btnCancel: "CANCEL",
    btnStopAlarm: "STOP ALARM",
    privacyTitle: "Privacy Policy",
    privacyText: "Duck Timer values your privacy. This app: Does not collect personal data, does not share information with third parties, and uses local storage to save your preferences.",
    newTimerTitle: "New Timer",
    modeDuck: "Duckling",
    modeDigital: "Digital",
    timeUpBody: "Time is up!",
    emptyTimeAlert: "Set a time first!",
    maxTimersAlert: "You have reached the limit of:",
    labelVibration: "Vibration on finish",
    labelVersion: "Version 1.0.0"
  },
  fr: {
    appTitle: "Duck Timer",
    settingsTitle: "Paramètres",
    labelAppearance: "Apparence",
    labelLanguage: "Langue",
    labelMaxTimers: "Max de Minuteurs",
    labelSupport: "Support et Suggestions",
    labelPrivacy: "Politique de Confidentialité",
    labelVersion: "Version",
    btnAccept: "ACCEPTER",
    btnCancel: "ANNULER",
    btnStopAlarm: "ARRÊTER L'ALARME",
    privacyTitle: "Politique de Confidentialité",
    privacyText: "Duck Timer respecte votre vie privée. Cette application : Ne collecte aucune donnée personnelle, ne partage aucune information avec des tiers et utilise le stockage local pour vos préférences.",
    newTimerTitle: "Nouveau Minuteur",
    modeDuck: "Caneton",
    modeDigital: "Digital",
    timeUpBody: "Le temps est écoulé !",
    emptyTimeAlert: "Réglez d'abord une heure !",
    maxTimersAlert: "Vous avez atteint la limite de :",
    labelVibration: "Vibration à la fin",
    labelVersion: "Version 1.0.0"
  },
  it: {
    appTitle: "Duck Timer",
    settingsTitle: "Impostazioni",
    labelAppearance: "Aspetto",
    labelLanguage: "Lingua",
    labelMaxTimers: "Massimo Timer",
    labelSupport: "Supporto e Suggerimenti",
    labelPrivacy: "Informativa sulla Privacy",
    labelVersion: "Versione",
    btnAccept: "ACCETTA",
    btnCancel: "ANNULLA",
    btnStopAlarm: "FERMA ALLARME",
    privacyTitle: "Informativa sulla Privacy",
    privacyText: "Duck Timer apprezza la tua privacy. Questa applicazione: Non raccoglie dati personali, non condivide informazioni con terzi e utilizza l'archiviazione locale per salvare le tue preferenze.",
    newTimerTitle: "Nuovo Timer",
    modeDuck: "Anatroccolo",
    modeDigital: "Digitale",
    timeUpBody: "Tempo scaduto!",
    emptyTimeAlert: "Imposta prima un orario!",
    maxTimersAlert: "Hai raggiunto il limite di:",
    labelVibration: "Vibrazione al termine",
    labelVersion: "Versione 1.0.0"
  },
  de: {
    appTitle: "Duck Timer",
    settingsTitle: "Einstellungen",
    labelAppearance: "Aussehen",
    labelLanguage: "Sprache",
    labelMaxTimers: "Max. Timer",
    labelSupport: "Support & Vorschläge",
    labelPrivacy: "Datenschutzerklärung",
    labelVersion: "Version",
    btnAccept: "AKZEPTIEREN",
    btnCancel: "ABBRECHEN",
    btnStopAlarm: "ALARM STOPPEN",
    privacyTitle: "Datenschutzerklärung",
    privacyText: "Duck Timer schätzt Ihre Privatsphäre. Diese App: Sammelt keine persönlichen Daten, gibt keine Informationen an Dritte weiter und verwendet den lokalen Speicher, um Ihre Einstellungen zu speichern.",
    newTimerTitle: "Neuer Timer",
    modeDuck: "Entchen",
    modeDigital: "Digital",
    timeUpBody: "Zeit ist abgelaufen!",
    emptyTimeAlert: "Stellen Sie zuerst eine Zeit ein!",
    maxTimersAlert: "Sie haben das Limit erreicht von:",
    labelVibration: "Vibration bei Ende",
    labelVersion: "Version 1.0.0"
  },
  pt: {
    appTitle: "Duck Timer",
    settingsTitle: "Configurações",
    labelAppearance: "Aparência",
    labelLanguage: "Idioma",
    labelMaxTimers: "Máximo de Timers",
    labelSupport: "Suporte e Sugestões",
    labelPrivacy: "Política de Privacidade",
    labelVersion: "Versão",
    btnAccept: "ACEITAR",
    btnCancel: "CANCELAR",
    btnStopAlarm: "PARAR ALARME",
    privacyTitle: "Política de Privacidade",
    privacyText: "Duck Timer valoriza sua privacidade. Este aplicativo: Não coleta dados pessoais, não compartilha informações com terceiros e usa o armazenamento local para salvar suas preferências.",
    newTimerTitle: "Novo Temporizador",
    modeDuck: "Patinho",
    modeDigital: "Digital",
    timeUpBody: "O tempo acabou!",
    emptyTimeAlert: "Defina um tempo primeiro!",
    maxTimersAlert: "Você atingiu o limite de:",
    labelVibration: "Vibração ao terminar",
    labelVersion: "Versão 1.0.0"
  }
};
// ... resto del código

let currentLang = "es";

function t(key) {
  return LANGUAGES[currentLang][key] || key;
}
